language: java
arch:
  - amd64
  - arm64
jdk:
  - openjdk8

install: true

cache:
  directories:
    - "$HOME/.m2"

before_script:
  - export MVN_HOME=$HOME/apache-maven-3.6.3
  - if [ ! -d $MVN_HOME/bin ]; then wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -P $HOME; tar xzvf $HOME/apache-maven-3.6.3-bin.tar.gz -C $HOME; fi
  - export PATH=$MVN_HOME/bin:$PATH
  - echo "MAVEN_OPTS='-Xmx1024m -XX:MaxMetaspaceSize=256m'" > ~/.mavenrc

script:
  - travis_wait 50 mvn --batch-mode --no-transfer-progress clean install cobertura:cobertura coveralls:report -DrepoToken="${COVERALLS_REPO_TOKEN}" -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "build failed!"
